using Godot;
using System;
using EventCallback;
public class ResourceManager : Node
{

    /*
    The power and nanites will be handled like red alets resources
    The power will be a constant draw so you have to balance the power to keep it above the low mark
    The nanites will be used like curency where certain building or upgrades will cost a once off nanite amount to build ar upgrade
    

    Power is generated by the power plants
    Nanites are constantly produced by the factoriesd

    */

    //The timer used to add resources every tick
    Timer resourceTimer;
    //The total amount of power that is available from the power plants combined
    int totalPower;
    //The current power available after the total power draw has been deducted
    int currentPower;
    //The total power being used by factories and weapons
    int totalPowerDraw;
    //The nanites that are available to be used
    int nanitesBanked;
    //Amount of nanites to be added every tick
    int nanitesAddition;

    // Called when the node enters the scene tree for the first time.
    public override void _Ready()
    {
        //Set the timer class to the instance in the scene
        resourceTimer = GetNode<Timer>("ResourceTimer");
    }
    //Modify the the ninite addition 
    private void OnModNanitesAdditionEvent(ModNanitesAdditionEvent mnae)
    {
        //Add the amount of nanites adition to the nanitesAddition value, it could increase or decrease the value depending on the sender
        nanitesAddition += mnae.amount;
    }
    //A once off function called when a cash or something of nanites is added as a once off item
    private void OnAddNanitesEvent(AddNanitesEvent ane)
    {
        //Add the one shot amount  of nanites to the bank
        nanitesBanked += ane.amount;
    }
    private void OnRemoveNanitesAmountEvent(RemoveNanitesAmountEvent rnae)
    {
        if (nanitesBanked > rnae.amount)
        {
            //Remove the amount of nanites from the 
            nanitesBanked -= rnae.amount;
            //Send back the true message to let the sender know the transaction was sucesfull
            rnae.done = true;
        }
    }
    private void OnModTotalPowerEvent(ModTotalPowerEvent mtpe)
    {
        //Add the power to thte total power 
        totalPower += mtpe.amount;
    }
    private void OnModPowerDrawEvent(ModPowerDrawEvent mpde)
    {
        //Check if there is enough power to supply the request
        if (currentPower >= mpde.amount)
        {
            totalPowerDraw += mpde.amount;
            //If the power was enough we return done else done is false by defualt
            mpde.done = true;
        }
    }
    public void OnResourceTimerTimeout()
    {
        //Add the adidtion nanites to the banked nanites
        nanitesBanked += nanitesAddition;
    }
    //Called to update the power in the UI
    private void UpdatePower()
    {

    }
}
